import { faker } from '@faker-js/faker';

export interface User {
  id: number;
  name: string;
}

// Create an array of 25 items, and fill it with 0s.
// We'll use this array to generate a list of users.
export const users = Array(25)
  .fill(0)
  // Map each item of the array to a new object, with an id and a name.
  // The variable _ is a common convention for a variable that is not going to be used.
  // It's a nice way to indicate to other developers that this variable is not important.
  .map((_, i) => ({
    // The id is the index of the item in the array.
    id: i,
    // The name is a fake name generated by the Faker library.
    name: faker.person.fullName(),
  }));

export const fetchUsers = async (search: string) => {
  await new Promise((resolve) => setTimeout(resolve, 1000));

  return users.filter((user) =>
    user.name.toLowerCase().includes(search.toLowerCase()),
  );
}